### ISSUE TITLE
Does this work with retrofit

### ISSUE THREAD

**Issue by entropitor** [SalomonBrys/Kotson#1]
Do you extend GSON or provide a similair API?

So will this work with for example [retrofit](http://square.github.io/retrofit/) ?

And does this works with kotlin models for deserialisation? (because GSON can only inject fields, not setters, so if I'm not mistaken, will not work with normal kotlin data classes)

**Comment by SalomonBrys** [comment]
Kotson is a Gson _extension_, it allows for easier usage of Gson with Kotlin.

In fact, I developped Kotson for a project in which I use retrofit, so there is no problem using retrofit with Kotson.
