### ISSUE TITLE
Kotlin rc

### ISSUE THREAD

**Issue by dave08** [SalomonBrys/Kotson#10]
Could you release for new kotlin version please?

Thanks for the great library!!

**Comment by SalomonBrys** [comment]
I'm working on it.
I'm waiting on Spek, which is used for unit tests. As soon as it is realeased for Kotlin-1.0.0-rc-1036, so will Kotson.

By the way, this will be Kotson 2 which is NOT compatible with Kotson 1. It's not much : just the way you declare typeAdapters, so if you used the `serialize*`, `deserialize*` or `createInstance*` functions, there will be a bit of change:

``` kotlin
gsonBuilder.registerTypeAdapter<MyType> {
    serialize {
        /*
            it.type: Type to serialize from
            it.context: GSon context
            it.src : Object to serialize
        */
    }

    deserialize {
        /*
            it.type: Type to deserialize to
            it.context: GSon context
            it.json : JsonElement to deserialize from
        */
    }

    createInstances {
        /*
            it: Type of instance to create
        */
    }
}

gsonBuilder.registerTypeHierarchyAdapter<MyType> {
    serialize { /* Same a above */ }
    deserialize { /* Same a above */ }
    createInstances { /* Same a above */ }
}

```

Anyway, the Spek author is working on the latest kotlin now, so it shouldn't be long ;)

**Comment by SalomonBrys** [comment]
Kotson 2.0.0 has landed in Maven Central ;)

**Comment by carlbenson** [comment]
Great work! Thanks!
