### ISSUE TITLE
Intermittently ignoring a custom type adaptor

### ISSUE THREAD

**Issue by sanity** [SalomonBrys/Kotson#13]
Here is my code:

```
    OutputStreamWriter(GZIPOutputStream(FileOutputStream("financials-0.0.1.json.gz"))).use {
        GsonBuilder()
                .registerTypeAdapter<Instant> {
                    serialize {
                        it.src.epochSecond.toJson()
                    }
                }
                .registerTypeAdapter<LocalDate> {
                    serialize {
                        it.src.toString().toJson()
                    }
                }
                .create().toJson(financials, it)
```

For some reason, it seems to be intermittently ignoring the Instant custom serializer and serializing an Instant field to `{"seconds":1452211200,"nanos":0}`

Sorry I can't reliably reproduce it, but can you think of any reason this could occur?

**Comment by SalomonBrys** [comment]
Sorry, I can't.
Instant is a final class, so there should not be any need for `registerTypeHierarchyAdapter`.
I've tried to reproduce this but I couldn't.

Are you using other means to configure GSon, such as the `JsonAdapter` annotation ?

**Comment by sanity** [comment]
A little confused, I used registerTypeAdapter, not registerTypeHierarchyAdapter ... ?

> Are you using other means to configure GSon, such as the JsonAdapter annotation ?

Nope, the code you see is the only code in which I use Kotson or Gson in my codebase.

**Comment by SalomonBrys** [comment]
Well, I have tried to reproduce this, without any success.
Indeed, you do not need `registerTypeHierarchyAdapter`, I was "thinking out loud".

I have no idea what's causing this, but I can't figure out any reason why the library would behave like that.

**Comment by SalomonBrys** [comment]
Hi,
any update ?
I've tried again all I could to reproduce, but couldn't...

**Comment by sanity** [comment]
No, haven't seen the problem since :(

**Comment by SalomonBrys** [comment]
I'm closing the issue for now.
If you encounter this behaviour again, feel free to reopen ;)

**Comment by sanity** [comment]
Roger wilco :)

On Thu, Mar 24, 2016 at 11:17 AM, Salomon BRYS notifications@github.com
wrote:

> I'm closing the issue for now.
> If you encounter this behaviour again, feel free to reopen ;)
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/SalomonBrys/Kotson/issues/13#issuecomment-200907171

## 

Ian Clarke
Blog: http://blog.locut.us/
