### ISSUE TITLE
library has an unsupported format

### ISSUE THREAD

**Issue by dsvoronin** [SalomonBrys/Kotson#2]
Seems 0.11.91.4 differs in some way

**Comment by dnlbauer** [comment]
same problem on 0.11.91.0 and 0.11.91.1

**Comment by aluxian** [comment]
I get this too, `0.11.91.1`

**Comment by SalomonBrys** [comment]
Kotson 1.1.0 (`com.github.salomonbrys.kotson:kotson:1.1.0`) is compatible with Kotlin 0.11.91.1. I forgot to update the readme when I updated. I haven't tested with 0.11.91.4, please reopen this issue if Kotson does not work for it ;)
