### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by dri94** [SalomonBrys/Kotson#39]
Does this support Kotlin's default values? With Gson when deserializing, if a value does not exist, it becomes null. Since this is supposed to support Kotson, does that value now get set to default value if it does not exist?

**Comment by ZiraiMode** [comment]
So what? Does this library support default values?

**Comment by SalomonBrys** [comment]
This library provides utilities for GSon usage in Kotlin.
In no way does this library intervenes in the serialization / deserialization process.
This is a question for GSon,.

**Comment by ZiraiMode** [comment]
Maybe you know some good libs that has build in support for kotlin? @SalomonBrys

**Comment by SalomonBrys** [comment]
KotlinX.Serialization

**Comment by ZiraiMode** [comment]
Will see it, thanks!
