### ISSUE TITLE
Kotlin 1.0 Beta Candidate support

### ISSUE THREAD

**Issue by peleteiro** [SalomonBrys/Kotson#6]
Please, consider upgrade Kotlin version.
Any code compiled with previous versions of Kotlin is not compatible with 1.0.

http://blog.jetbrains.com/kotlin/2015/10/kotlin-1-0-beta-candidate-is-out/

**Comment by SalomonBrys** [comment]
Working on it

**Comment by SalomonBrys** [comment]
Done (v1.5.0)

**Comment by peleteiro** [comment]
Thank you!

**Comment by iamyellow** [comment]
hey! I'm getting the -kotson-1.5.0.jar has an unsupported format...- message, though I'm using 1.0.0-beta-1038 (checked gradle.build and also kotlin plugins on the latest stable Android Studio). it's just me? thanks!

**Comment by peleteiro** [comment]
Upgrade to 1.5.1. It fixes this problem.
