### ISSUE TITLE
Kotlin library 'kotson-1.5.0.jar' has an unsupported format

### ISSUE THREAD

**Issue by UnknownJoe796** [SalomonBrys/Kotson#8]
When I attempt to use the new versions of Kotlin and Kotson, I get the error "Kotlin library 'kotson-1.5.0.jar' has an unsupported format.  Please update the library or plugin".  Any idea what's going on?

**Comment by SalomonBrys** [comment]
What version of Kotlin compiler / stdlib / idea plugin are you using ?

**Comment by yoavst** [comment]
Same here. Using latest beta.

Using jitpack version for latest commit. Works great.

**Comment by dsvoronin** [comment]
Same, my own build works, maven-central's one - same error

**Comment by SalomonBrys** [comment]
I've re-publish it with the version `1.5.1`. My guess is that when publishing 1.5.0, I forgot to clean, and gradle re-packaged some .class files that did not change.

**Comment by SalomonBrys** [comment]
Version `1.5.1` works.

**Comment by yoavst** [comment]
@SalomonBrys RC was released, please update :)

**Comment by SalomonBrys** [comment]
See #10 ;)
