### ISSUE TITLE
fromJson should return not nullable

### ISSUE THREAD

**Issue by yoavst** [SalomonBrys/Kotson#9]
Since `Gson.fromJson` return null only if string is null, it can return not a nullable type.

**Comment by SalomonBrys** [comment]
Unfortuately, that's not true as `Gson().fromJson<Whatever>("null") == null`.

So `fromJson` does returns null when given the String "null".

**Comment by yoavst** [comment]
I think it should be based on null ability of the generic parameter

**Comment by SalomonBrys** [comment]
What do you mean ?

**Comment by yoavst** [comment]
In my code, I use ``!!` immediately after every `fromJson`. If I would like it to be nullable, I would use `Whatever?`.

**Comment by SalomonBrys** [comment]
I see your point.

**Comment by SalomonBrys** [comment]
v1.7.0 corrects this

**Comment by kubanychlocal** [comment]
Needs simple sample of using Kotson.
This does not work
`import com.github.salomonbrys.kotson.*
import com.google.gson.*

fun main (args: Array <String>) {
    val obj:JsonObject = jsonObject(
            "name" to "kotson",
            "files" to 4
    )
    println(" ${obj}")
    class Person(public val obj: JsonObject) {
        val name: String by obj.byString("name") 
        val files: Int by obj.byInt("files")   
    }
    val person=Gson().fromJson(obj,Person ::class.java)
}`
